### ISSUE TITLE
Implement Rules

### ISSUE THREAD

**Issue by grysvn** [grayma/plm18_groupg#2]
We need Rule to do act as a validation for a single thing in the game. Every rule will be ran through on the validation of a move. Moves are a collection of old and new game state and old and new player state.

So a Rule will essentially compare old and new game and player state, look for a difference that it doesn't like (each Rule will be one particular thing), and then return false (?) if it doesn't like a state change? The thing I'm not sure about is if Rule will access the state in the Game object, or what.

Because this is Python and a lot of stuff is loosey-goosey, I don't want to either over-couple certain components, make abstraction/implementation a PITA, or just do it badly in general, so I would love to hear thoughts on this. I think what I have above is good, but I would love someone to shoot it down.

**Comment by willglas** [comment]
So just to clarify... What you're proposing here is a Rule class which will have many instances, and each instance will validate a different, unique rule for the game? So then each time a move is made by a player, each Rule will be passed the game state, player state, and the move, and then validate that move against the game/player state?

**Comment by grysvn** [comment]
First, yes, Rule will have many instances. Second, yes, I haven't decided on if rules get passed the game state or they access a reference to it because if they were passed a value every time that's an efficiency 💩. I'm guessing going with the latter.

**Comment by grysvn** [comment]
So my current thought with Rule is that it'll take in a key that represents an object in the game state, and then it'll take an evaluation function ( so def __init__(self, key, evaluation): ) and then evaluate that key's value with the evaluation function. If the game state is valid *based on that one rule* then it returns true. If not, then it returns false.

**Comment by grysvn** [comment]
So we decided not to implement rules, rules are inherently a part of the game by the move functions which validate moves.
