### ISSUE TITLE
How to handle player/game state?

### ISSUE THREAD

**Issue by grysvn** [grayma/plm18_groupg#3]
This issue is for deciding how to handle player and game state (the first is like the player's deck, the second is the center deck or something similar). It includes but is not limited to:

- What object are we storing player state in (player? or game?). If stored in player, would a specific player object be created per game? HeartsPlayer? Will the game have to keep track (have player states as a member of game) of player states for validation purposes or can it just access like player[n].state?
- What exactly will be stored in the state objects? Decks?

**Comment by willglas** [comment]
Storing player state in player objects is definitely the way to go in my opinion. One way we could go about this is to define an abstract base class Player (don't think python has explicit interface functionality?) then have HeartsPlayer and Crazy8Player extend that class.

**Comment by grysvn** [comment]
I agree on all points. What I've been leaning towards.

**Comment by grysvn** [comment]
Got this figured out. Game state stored in a dict in game object, player state, stored in a dict within player within game state (game state holds players).
